### ISSUE TITLE
Fix Invisible Armor

### ISSUE THREAD

**Issue by GriffinCodes** [ProjectEdenGG/Issues#406]
Converting from Skript to Java introduced a lot of bugs, namely armor not appearing/disappearing and repeated equip sounds. Need to revisit

**Comment by lexikiq** [comment]
Should be delisted from the /store until fixed

**Comment by lexikiq** [comment]
has been delisted 👍🏻

**Comment by WakkaFlocka239** [comment]
Any updates on this? It's listed as priority.

**Comment by qixils** [comment]
Fixed by [aa1a8f8](https://github.com/ProjectEdenGG/Nexus/commit/aa1a8f836b9cdefdecccfea408dcac1880961fb3), [e54bb11](https://github.com/ProjectEdenGG/Nexus/commit/e54bb11727fe373d39616d473481a01c589b9ac3), and [cfa1fca](https://github.com/ProjectEdenGG/Nexus/commit/cfa1fca05c5f9d3bfc638dfa291889b008df586b)
