### ISSUE TITLE
/vote improvements

### ISSUE THREAD

**Issue by JustSteveThings** [ProjectEdenGG/Issues#504]
I was trying to teach kdk1503 about the prompted by kodabot to vote system that used to work in 2018 but nothing i tried koda wouldn't respond to me. 

![](https://cdn.discordapp.com/attachments/134055812233428992/806502994249252934/unknown.png)

![](https://cdn.discordapp.com/attachments/134055812233428992/806503186462146560/unknown.png)

It's still working as ash gets messaged daily 
![](https://cdn.discordapp.com/attachments/134055812233428992/806504417770733578/Screenshot_20210203-134225_Discord.jpg)

**Comment by Pugabyte** [comment]
When we moved everything away from the old language in order to update to 1.15, this was not fully carried over, as it was pretty infrequently used. You still get voting notifications whenever a vote expires, there's just not a lot of commands you can run. I can bring back the `/vote` command but I don't want to reintroduce the settings

**Comment by JustSteveThings** [comment]
The vote thing is enough

**Comment by GriffinCodes** [comment]
Adding to this issue: 
- [x] Improve /vote with personal vote times
