### ISSUE TITLE
store package permissions not applying to players

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#786]
Several reports of people not getting the permissions they bought

**Comment by GriffinCodes** [comment]
What reports? I only know of DiamondMiner's vaults

**Comment by qixils** [comment]
Worg recently had an issue where their plot count wasn't upgraded but that's unrelated 🤷🏻‍♀️

**Comment by WakkaFlocka239** [comment]
diamondminers reports

#bugs
<img src=https://i.imgur.com/Q9W1nou.png>
she didn't get her pets permission nor her hat permission

I've had to fix several peoples permissions, I would consider this an issue worth opening.

**Comment by GriffinCodes** [comment]
Drier never purchased /hat

no idea how it would have printed `[LP] DrierMonster142 now inherits permissions from store.disguises.aquatic in context global.` but not actually added the parent, but regardless i completely rewrote it this morning to use the API instead of running a console command, and ive just tested on myself and it works
